name: 'Continuous integration'
on: ['push', 'pull_request']
jobs:
  php-cs:
    runs-on: 'ubuntu-latest'
    name: 'PHP coding style'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '7.4'
          coverage: 'none'
          extensions: 'json, mbstring, tokenizer'
          tools: 'composer-normalize, php-cs-fixer:2.16.4'
        env:
          update: true

      - name: 'Display tools versions'
        run: |
          composer-normalize --version
          php-cs-fixer --version

      - name: 'Check coding style'
        run: 'php-cs-fixer fix --diff --dry-run --using-cache=false'

      - name: 'Check composer.json normalization'
        run: 'composer-normalize --diff --dry-run --no-update-lock'